### ISSUE TITLE
UAGS Scraping. (How to)

### ISSUE THREAD

**Issue by ransom1122** [HoraceAndTheSpider/UAGS#2]

**Comment by ransom1122** [comment]
Hi could someone take the time out on explaining how i install this scraper with retropie please?

**Comment by HoraceAndTheSpider** [comment]
Added to readme. :)

**Comment by ransom1122** [comment]
Thank you kind Sir. I will try this tomorrow. This is by far the best amiga experience I have ever had away from my real amiga hardware. Simply Amazing
